### PR TITLE
Returns Aphrodite instance, rather than raise an exception, if the config requested is identical at the running one

### PR DESCRIPTION
**Pull request by rpelisse**

### CODE REVIEW

**Comment by ryanemerson** [comment]
@rpelisse The logic looks good, but your IDE has gone a bit nuts with the formatting.  Can you re-push the commit with only changes to the relevant parts. I.e. no changes to the constructor, toString methods and Streams formatting.  I just want to make sure that the diffs only show relevant changes

**Comment by rpelisse** [comment]
@ryanemerson actually I had to use Eclipse formatting, to pass the checkstyle part of the build. I'm using the [same configs as the one JBoss / WFLY](https://github.com/wildfly/wildfly-core/tree/master/ide-configs/eclipse) - are you using them too ?

**Comment by ryanemerson** [comment]
@rpelisse I use intellij, so I can't use them. The previous code was passing the checkstyle fine on the cmd line for me

**Comment by rpelisse** [comment]
@ryanemerson yeah, so you are telling me : "It's work on my machine" :)

We need a better to handle that (gosh I wish we could commit AST rather than actual text-based code). I mean we cannot expect every pull request to magically match your IDE settings. So we either align to an existing one (thus I used the one from Wildfly) or we provide one (seems to be too much work for what it is worth).

**Comment by ryanemerson** [comment]
@rpelisse I wasn't expecting you to magically follow my IDE settings :) just limit the code changes to those that are relevant to the bug fix/new features (as is the case with most projects) and make sure that mvn install passes all tests

**Comment by rpelisse** [comment]
Superseed by https://github.com/jboss-set/aphrodite/pull/20

**Pull request closed without merging**
