### PR TITLE
Add history support of the JiraIssue.

### PR DESCRIPTION
**Pull request by MMarus**

### CODE REVIEW

**Comment by elguardian** [comment]
looks good to me.
@baranowb mind to look at this ?

**Comment by rpelisse** [comment]
@baranowb I would like to merge https://github.com/jboss-set/bug-clerk/pull/58 into Bugclerk code base, but its depends on this PR. Can you review it ? (or just let me know if you are OK with merging it, and I'll take care of that)

**Comment by baranowb** [comment]
Weird, I did not see notofication up until today.

**Comment by MMarus** [comment]
Moving conversation from [1] to correct PR:
@wolfc did say: 
This needs thought [2]. Every loop is a performance impact by design.
[1] https://github.com/jboss-set/aphrodite/pull/134#discussion-diff-124002254R177
[2] https://github.com/jboss-set/aphrodite/pull/130/files#diff-3511e058052f770e441e3c22939ceef1R177

@mmarus:

Romain mentioned that it would be good not to expose the Jira's objects (e.q. ChangelogItem and ChangelogGroup) through the aphrodite.
That's why I need to copy those jira's ChangelogItem-s into the aphrodite's JiraChangelogItems.
Could you please advice me how to do that without the loop?

Another possibility is try to do some lazy loading with query like this https://issues.jboss.org/rest/api/latest/issue/JBEAP-9466?expand=changelog&fields=summary and parse
the results like methods in https://github.com/jboss-set/aphrodite/blob/master/jira/src/main/java/org/jboss/set/aphrodite/jira/rest/client/internal/async/AsynchronousAgileRestClient.java with custom ChangelogJsonParser. Sadly this internally uses a loop to parse the json data as well.
Not to mention that it would increase number of connections to jira API by 1 for each issue requesting the changelog.

Yet another way, is to implement our own AsynchronousSearchRestClient with our own SearchResultJsonParser.
The SearchResultJsonParser could parse the search result straight into aphrodite's JiraChangelogGroup instead of the Jira's ChangelogGroup.
However, this could be an extensive thing.

I have created a new branch to show how the last option could look like master...MMarus:CustomJsonParser . It extends the jira's Issue with our Changelog types. Our custom Json parser will parse the history only to our types (e.q. JiraChangelogGroups and JiraChangelogItems).

**Pull request merged**
