### PR TITLE
Add a field trackerType on Issue, so that client can figure out easily where the issue comes from

### PR DESCRIPTION
**Pull request by rpelisse**
This is mostly aimed at Bugclerk, to allow it to skip some checks that does not apply to the tracker. It's a proposal, if you don't feel it should integrated, I'll hack that into a static method in Bugclerk code base.

### CODE REVIEW

**Comment by ryanemerson** [comment]
@rpelisse I'm not against it, as it doesn't change behaviour and is additional information.  What do you think @elguardian ?

p.s. It will have to compile in order for it to be merged :)

**Comment by rpelisse** [comment]
duh, forgot to commit the compilation fixes... :$

**Comment by elguardian** [comment]
I'm ok with this as it is just a transient field. maybe we should remove the set method as this is read-only  and set the attribute in the constructor instead.

**Comment by elguardian** [comment]
don't close, this is ok. just add the other commit and squash, then push again the branch.

**Comment by rpelisse** [comment]
elguardian more than OK with that, but in this case we need to add it to the constructor.

**Comment by ryanemerson** [comment]
@elguardian Sounds good to me. One possible problem is if someone provides there own IssueTrackerService implementation via the ServiceLoader (not sure if that will ever actually happen), so maybe we should a TracerType.Custom field to cover that case.

**Comment by rpelisse** [comment]
@ryanemerson I would wait for someone to provide such implementation to do it (but I'm french we are known to be that kind of lazy ;) )

**Comment by rpelisse** [comment]
darn i did not saw I had closed the PR, sorry....

**Comment by ryanemerson** [comment]
@rpelisse yeah lets keep it simple for now. I think we should remove the set method and use the constructor as @elguardian suggested though

**Comment by ryanemerson** [comment]
@rpelisse Also rebasing as a single commit would make the history look a lot cleaner

**Comment by rpelisse** [comment]
@ryanemerson will, do, just wait for @elguardian to sign off adding the field to the constructor, to implement that and rebase the all thing.

**Comment by elguardian** [comment]
go for it.

**Comment by rpelisse** [comment]
OK, done - please review and merge :)

**Comment by ryanemerson** [comment]
@rpelisse Merged, thanks!

**Pull request merged**
