### PR TITLE
issue type COMPONENT does not work.

### PR DESCRIPTION
**Pull request by soul2zimate**
it does not match JIRA / Bugziila type "Component Upgrade", and gets default value "UNDEFINED"

### CODE REVIEW

**Comment by ryanemerson** [comment]
@soul2zimate I had to make a few more changes for this to work with the Bugzilla update logic, see ce91d20. Thanks

**Comment by soul2zimate** [comment]
the fix works for Bugziila, but https://issues.jboss.org/browse/JBEAP-4223 still returns UNDEFINED as there are two spaces between Component and Upgrade in jira field.

**Comment by ryanemerson** [comment]
@soul2zimate Argh nightmare. I tested it on https://issues.stage.jboss.org and it works fine, but it doesn't work on https://issues.jboss.org. I'll push another commit :)

**Comment by ryanemerson** [comment]
33b57fb should fix it

**Pull request closed without merging**
